#!/usr/bin/env node
/* ============================================================================
   Bodhi Map for FIBO — OKF bundle -> browser graph data.
   Usage:  node scripts/okf.js build   # knowledge/ + okf.config.js -> js/data.js

   The OKF bundle in knowledge/ is the source of truth (GENERATED by the Python ETL;
   see CLAUDE.md). This reads it and okf.config.js and emits js/data.js: nodes +
   typed, PROVENANCE-tagged edges for the Cytoscape map. Curated cross-domain bridges
   (knowledge/bridges/) become edges with provenance: curated.

   Adapted from Bodhi's scripts/okf.js (MIT, © Sanjeev Azad). Unlike Bodhi's flat
   cluster/id.md bundle, ours is module-nested (basenames collide by design), and our
   frontmatter relations are inline {type,target,provenance} objects — both handled here.
   ============================================================================ */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const BUNDLE = path.join(ROOT, 'knowledge');
const DATA_JS = path.join(ROOT, 'js', 'data.js');
const CONFIG = require(path.join(ROOT, 'okf.config.js'));

// A collision-safe, selector-safe node id from a bundle path. Our paths are unique
// (they mirror unique IRIs); join segments with '__' (never present in FIBO names).
function pathToId(relPath) {
  return relPath.replace(/\.md$/, '').split('/').join('__');
}
function targetToId(target) {           // relation target: "/LOAN/.../Loan.md"
  return pathToId(String(target).replace(/^\//, ''));
}

// ---- frontmatter parsing (our controlled shape: scalars, inline [lists], and a
// `relations:` block of inline {type,target,provenance} objects) --------------------
function stripQuotes(s) {
  s = s.trim();
  return (s.startsWith('"') && s.endsWith('"')) ? s.slice(1, -1) : s;
}
function parseInlineList(s) {            // "[LOAN, Release]" -> ["LOAN","Release"]
  return s.replace(/^\[|\]$/g, '').split(',').map((x) => x.trim()).filter(Boolean);
}
function parseRelationObj(s) {           // "{type: is-a, target: \"/x.md\", provenance: fibo}"
  const type = (s.match(/type:\s*([^,}]+)/) || [])[1];
  const target = (s.match(/target:\s*("?[^,}]+?"?)\s*(?:,|})/) || [])[1];
  const prov = (s.match(/provenance:\s*([^,}]+)/) || [])[1];
  if (!type || !target) return null;
  return { type: type.trim(), target: stripQuotes(target), provenance: (prov || 'fibo').trim() };
}
function parseFrontmatter(text) {
  if (!text.startsWith('---')) return { fm: {}, body: text };
  const end = text.indexOf('\n---', 3);
  const fmText = text.slice(3, end).replace(/^\n/, '');
  const body = text.slice(end + 4).replace(/^\n+/, '');
  const fm = { relations: [] };
  let inRelations = false;
  for (const line of fmText.split('\n')) {
    const rel = line.match(/^\s+-\s*\{(.*)\}\s*$/);
    if (inRelations && rel) { const r = parseRelationObj(rel[1]); if (r) fm.relations.push(r); continue; }
    const m = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
    if (!m) continue;
    const key = m[1]; const val = m[2].trim();
    if (key === 'relations') { inRelations = true; continue; }
    inRelations = false;
    if (val.startsWith('[')) fm[key] = parseInlineList(val);
    else if (val === 'true' || val === 'false') fm[key] = (val === 'true');
    else fm[key] = stripQuotes(val);
  }
  return { fm, body };
}
function detailFromBody(body) {          // text before the first '### ' / '## ' heading
  const stop = body.search(/\n#{2,3}\s/);
  return (stop === -1 ? body : body.slice(0, stop)).trim();
}

function walkMd(dir, acc) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) walkMd(p, acc);
    else if (entry.name.endsWith('.md') && entry.name !== 'index.md' && entry.name !== 'log.md') acc.push(p);
  }
  return acc;
}

function build() {
  const files = walkMd(BUNDLE, []).sort();
  const nodes = [];
  const edges = [];
  const bridgeFiles = [];

  files.forEach((file) => {
    const rel = path.relative(BUNDLE, file);
    const { fm, body } = parseFrontmatter(fs.readFileSync(file, 'utf8'));
    if (!fm.type) return;
    if (fm.type === 'Cross-Domain Relation') { bridgeFiles.push({ fm }); return; }

    const cluster = rel.split(path.sep)[0];
    const maturity = (fm.tags || []).find((t) => CONFIG.MATURITY_LEVEL[t]) || null;
    const id = pathToId(rel);
    nodes.push({
      id, label: fm.title || id, type: fm.type, cluster,
      level: CONFIG.MATURITY_LEVEL[maturity] || 3, maturity,
      core: fm.core === true,
      summary: fm.description || '',
      detail: detailFromBody(body),
      definitionProvenance: fm.definition_provenance || 'fibo',
      resource: fm.resource,
    });
    (fm.relations || []).forEach((e) => {
      edges.push({ s: id, t: targetToId(e.target), r: e.type, provenance: e.provenance });
    });
  });

  const ids = new Set(nodes.map((n) => n.id));

  // Curated bridges -> edges (source_class -> relation target), provenance: curated.
  bridgeFiles.forEach(({ fm }) => {
    const e = (fm.relations || [])[0];
    if (!fm.source_class || !e) return;
    edges.push({
      s: targetToId(fm.source_class), t: targetToId(e.target), r: e.type,
      provenance: 'curated', bridge: true,
      kind: fm.kind, rationale: fm.rationale, citation: fm.citation,
    });
  });

  // Keep only edges whose endpoints are emitted nodes; report the rest (pending links).
  const resolved = edges.filter((e) => ids.has(e.s) && ids.has(e.t));
  const pending = edges.length - resolved.length;

  // Deterministic ordering.
  const cOrder = Object.keys(CONFIG.CLUSTERS);
  nodes.sort((a, b) => (cOrder.indexOf(a.cluster) - cOrder.indexOf(b.cluster)) || a.id.localeCompare(b.id));
  resolved.sort((a, b) => a.s.localeCompare(b.s) || a.r.localeCompare(b.r) || a.t.localeCompare(b.t));

  const GRAPH = { nodes, edges: resolved };
  const out =
`/* ============================================================================
   Bodhi Map for FIBO — GENERATED FILE. Do not edit by hand.
   Source of truth: the OKF bundle in knowledge/ (+ okf.config.js for vocab).
   Regenerate with:  node scripts/okf.js build   (or: make map)
   ============================================================================ */
const CLUSTERS = ${JSON.stringify(CONFIG.CLUSTERS, null, 2)};
const LEVELS = ${JSON.stringify(CONFIG.LEVELS, null, 2)};
const RELATIONS = ${JSON.stringify(CONFIG.RELATIONS, null, 2)};
const PROVENANCE = ${JSON.stringify(CONFIG.PROVENANCE, null, 2)};
const RELEASE = ${JSON.stringify(CONFIG.RELEASE, null, 2)};
const GRAPH = ${JSON.stringify(GRAPH, null, 2)};
`;
  fs.mkdirSync(path.dirname(DATA_JS), { recursive: true });
  fs.writeFileSync(DATA_JS, out);
  const core = nodes.filter((n) => n.core).length;
  const bridges = resolved.filter((e) => e.bridge).length;
  console.log(`build ✓  ${nodes.length} nodes (${core} core), ${resolved.length} edges `
    + `(${bridges} curated bridges) -> ${path.relative(ROOT, DATA_JS)}`);
  if (pending) console.log(`  ${pending} edges dropped (targets not emitted — CMNS/LCC/other domains)`);
}

const cmd = process.argv[2];
if (cmd === 'build') build();
else { console.error('Usage: node scripts/okf.js build'); process.exit(1); }
