#!/usr/bin/env node
/* ============================================================================
   Bodhi Map for FIBO — OKF bundle -> browser graph data.
   Usage:  node scripts/okf.js build   # knowledge/ + okf.config.js -> js/data.js

   The OKF bundle in knowledge/ is the source of truth (GENERATED by the Python ETL;
   see CLAUDE.md). This reads it and okf.config.js and emits js/data.js in the exact shape
   the Cytoscape renderer (js/graph.js, forked verbatim from Bodhi) consumes: CLUSTERS /
   LEVELS / RELATIONS / RELEASE and a GRAPH of nodes + typed, PROVENANCE-tagged edges plus
   the resolved decisionTree / guidedPath / comparisons flows.

   Forked from Bodhi's scripts/okf.js (MIT, © Sanjeev Azad). Unlike Bodhi's flat
   cluster/id.md bundle, ours is module-nested (basenames collide by design) and our
   frontmatter relations are inline {type,target,provenance} objects — both handled here.
   Flows in okf.config.js reference concepts by FIBO IRI; we resolve each to a node id.
   ============================================================================ */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const BUNDLE = path.join(ROOT, 'knowledge');
const DATA_JS = path.join(ROOT, 'js', 'data.js');
const CONFIG = require(path.join(ROOT, 'okf.config.js'));

function pathToId(relPath) { return relPath.replace(/\.md$/, '').split('/').join('__'); }
function targetToId(target) { return pathToId(String(target).replace(/^\//, '')); }

// FIBO module name -> human label: "FunctionalEntities" -> "Functional Entities",
// "DebtAndEquities" -> "Debt & Equities", "RealEstateLoans" -> "Real Estate Loans".
function humanize(s) {
  return s.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/\bAnd\b/g, '&').replace(/\s+/g, ' ').trim();
}

// --- colour: shade a domain's base hue across its sub-clusters (same family, distinct) ---
function hexToHsl(hex) {
  const m = /^#?([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex) || ['', '80', '80', '80'];
  let r = parseInt(m[1], 16) / 255, g = parseInt(m[2], 16) / 255, b = parseInt(m[3], 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b); let h = 0, s = 0; const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min; s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = (g - b) / d + (g < b ? 6 : 0); else if (max === g) h = (b - r) / d + 2; else h = (r - g) / d + 4;
    h /= 6;
  }
  return [h * 360, s * 100, l * 100];
}
function hslToHex(h, s, l) {
  h /= 360; s /= 100; l /= 100; let r, g, b;
  if (s === 0) { r = g = b = l; } else {
    const f = (p, q, t) => { if (t < 0) t += 1; if (t > 1) t -= 1; if (t < 1 / 6) return p + (q - p) * 6 * t;
      if (t < 1 / 2) return q; if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6; return p; };
    const q = l < 0.5 ? l * (1 + s) : l + s - l * s, p = 2 * l - q;
    r = f(p, q, h + 1 / 3); g = f(p, q, h); b = f(p, q, h - 1 / 3);
  }
  const to = (x) => ('0' + Math.round(x * 255).toString(16)).slice(-2);
  return '#' + to(r) + to(g) + to(b);
}
function shade(base, i, n) {
  const [h, s] = hexToHsl(base);
  const t = n <= 1 ? 0.5 : i / (n - 1);
  const L = 44 + t * 26;                 // 44%..70% lightness spread
  const H = (h + (t - 0.5) * 26 + 360) % 360;   // +/-13deg hue rotation, stays in family
  return hslToHex(H, Math.max(50, Math.min(85, s)), L);
}

// Expand domains -> module sub-clusters (shaded) + legend groups (grouped by domain).
function buildClusters(domMods) {
  const CLUSTERS = {}; const CLUSTER_GROUPS = [];
  const domains = Object.keys(CONFIG.DOMAINS).sort((a, b) => CONFIG.DOMAINS[a].order - CONFIG.DOMAINS[b].order);
  domains.forEach((dom) => {
    const mods = [...(domMods[dom] || [])].sort();
    if (!mods.length) return;
    const clusterIds = [];
    mods.forEach((m, i) => {
      const id = dom + '__' + m;
      CLUSTERS[id] = { label: humanize(m), color: shade(CONFIG.DOMAINS[dom].color, i, mods.length), domain: dom };
      clusterIds.push(id);
    });
    CLUSTER_GROUPS.push({ title: CONFIG.DOMAINS[dom].label, clusters: clusterIds });
  });
  return { CLUSTERS, CLUSTER_GROUPS };
}

// ---- frontmatter parsing (scalars, inline [lists], `relations:` block of inline objects) --
function stripQuotes(s) { s = s.trim(); return (s.startsWith('"') && s.endsWith('"')) ? s.slice(1, -1) : s; }
function parseInlineList(s) { return s.replace(/^\[|\]$/g, '').split(',').map((x) => x.trim()).filter(Boolean); }
function parseRelationObj(s) {
  const type = (s.match(/type:\s*([^,}]+)/) || [])[1];
  const target = (s.match(/target:\s*("?[^,}]+?"?)\s*(?:,|})/) || [])[1];
  const prov = (s.match(/provenance:\s*([^,}]+)/) || [])[1];
  if (!type || !target) return null;
  return { type: type.trim(), target: stripQuotes(target), provenance: (prov || 'fibo').trim() };
}
function parseFrontmatter(text) {
  if (!text.startsWith('---')) return { fm: {}, body: text };
  const end = text.indexOf('\n---', 3);
  const fmText = text.slice(3, end).replace(/^\n/, '');
  const body = text.slice(end + 4).replace(/^\n+/, '');
  const fm = { relations: [] };
  let listKey = null;                    // current `key:` whose indented `- …` items follow
  for (const line of fmText.split('\n')) {
    const item = line.match(/^\s+-\s*(.*)$/);
    if (listKey && item) {
      const raw = item[1].trim();
      if (listKey === 'relations') {
        const o = raw.match(/^\{(.*)\}$/); const r = o && parseRelationObj(o[1]); if (r) fm.relations.push(r);
      } else { (fm[listKey] = fm[listKey] || []).push(stripQuotes(raw)); }
      continue;
    }
    const m = line.match(/^([A-Za-z0-9_]+):\s*(.*)$/);
    if (!m) continue;
    const key = m[1]; const val = m[2].trim();
    if (val === '') { listKey = key; if (key !== 'relations') fm[key] = []; continue; }   // list block follows
    listKey = null;
    if (val.startsWith('[')) fm[key] = parseInlineList(val);
    else if (val === 'true' || val === 'false') fm[key] = (val === 'true');
    else fm[key] = stripQuotes(val);
  }
  return { fm, body };
}

function walkMd(dir, acc) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) walkMd(p, acc);
    else if (entry.name.endsWith('.md') && entry.name !== 'index.md' && entry.name !== 'log.md') acc.push(p);
  }
  return acc;
}

// Resolve a flow's FIBO IRIs -> node ids; drop steps/rows that don't resolve.
function resolveFlows(idByIri) {
  const id = (iri) => idByIri[iri];
  const gp = CONFIG.GUIDED_PATH;
  const guidedPath = { title: gp.title, steps: gp.steps.map((s) => ({ id: id(s.id), note: s.note })).filter((s) => s.id) };

  const dt = CONFIG.DECISION_TREE;
  const steps = {};
  Object.entries(dt.steps).forEach(([k, step]) => {
    steps[k] = { q: step.q, a: step.a.map((ans) => {
      const out = { label: ans.label };
      if (ans.next) out.next = ans.next;
      if (ans.why) out.why = ans.why;
      if (ans.rec) { const r = id(ans.rec); if (r) out.rec = r; else return null; }
      if (ans.then) out.then = ans.then;
      return out;
    }).filter(Boolean) };
  });
  const decisionTree = { start: dt.start, steps };

  const comparisons = CONFIG.COMPARISONS.map((cmp) => ({
    ...cmp,
    rows: cmp.rows.map((r) => { const nid = id(r.id); return nid ? { ...r, id: nid } : null; }).filter(Boolean),
  })).filter((c) => c.rows.length);

  return { guidedPath, decisionTree, comparisons };
}

function build() {
  const files = walkMd(BUNDLE, []).sort();
  const nodes = [];
  const edges = [];
  const bridgeFiles = [];
  const idByIri = {};
  const domMods = {};                                      // domain -> Set(module) present in data

  files.forEach((file) => {
    const rel = path.relative(BUNDLE, file);
    const { fm } = parseFrontmatter(fs.readFileSync(file, 'utf8'));
    if (!fm.type) return;
    if (fm.type === 'Cross-Domain Relation') { bridgeFiles.push(fm); return; }

    const seg = rel.split(path.sep);
    const domain = seg[0];
    if (!CONFIG.DOMAINS[domain]) return;                   // only emit domains we render
    const module = seg[1] || domain;                       // FIBO module = the sub-cluster
    const cluster = domain + '__' + module;
    (domMods[domain] = domMods[domain] || new Set()).add(module);
    const maturity = (fm.tags || []).find((t) => CONFIG.MATURITY_LEVEL[t]) || null;
    const id = pathToId(rel);
    if (fm.resource) idByIri[fm.resource] = id;
    nodes.push({
      id, label: fm.title || id, type: fm.type, cluster, domain,
      level: CONFIG.MATURITY_LEVEL[maturity] || 3, maturity: maturity || 'n/a',
      core: fm.core === true, summary: fm.description || '',
      detail: fm.detail || '', examples: fm.examples || [], synonyms: fm.synonyms || [],
      detailProvenance: fm.detail_provenance || 'fibo',
      examplesProvenance: fm.examples_provenance || 'fibo',
      definitionProvenance: fm.definition_provenance || 'fibo',
      // The FIBO IRI is the audit citation — surfaced in the panel's References section.
      refs: fm.resource ? [{ t: 'FIBO ontology — ' + String(fm.resource).split('/').pop(), u: fm.resource }] : [],
    });
    (fm.relations || []).forEach((e) => {
      edges.push({ s: id, t: targetToId(e.target), r: e.type, provenance: e.provenance });
    });
  });

  const ids = new Set(nodes.map((n) => n.id));

  bridgeFiles.forEach((fm) => {
    const e = (fm.relations || [])[0];
    if (!fm.source_class || !e) return;
    edges.push({ s: targetToId(fm.source_class), t: targetToId(e.target), r: e.type,
      provenance: 'curated', bridge: true });
  });

  const flows = resolveFlows(idByIri);
  for (let i = 0; i < flows.guidedPath.steps.length - 1; i++) {
    edges.push({ s: flows.guidedPath.steps[i].id, t: flows.guidedPath.steps[i + 1].id, r: 'path' });
  }

  const resolved = edges.filter((e) => ids.has(e.s) && ids.has(e.t));
  const pending = edges.length - resolved.length;

  const { CLUSTERS, CLUSTER_GROUPS } = buildClusters(domMods);
  const cOrder = Object.keys(CLUSTERS);
  nodes.sort((a, b) => (cOrder.indexOf(a.cluster) - cOrder.indexOf(b.cluster)) || a.id.localeCompare(b.id));
  resolved.sort((a, b) => (a.r === 'path' ? 1 : 0) - (b.r === 'path' ? 1 : 0)
    || a.s.localeCompare(b.s) || a.r.localeCompare(b.r) || a.t.localeCompare(b.t));

  const GRAPH = { nodes, edges: resolved, decisionTree: flows.decisionTree,
    guidedPath: flows.guidedPath, comparisons: flows.comparisons };
  const out =
`/* ============================================================================
   Bodhi Map for FIBO — GENERATED FILE. Do not edit by hand.
   Source of truth: the OKF bundle in knowledge/ (+ okf.config.js for vocab/flows).
   Regenerate with:  node scripts/okf.js build   (or: make map)
   ============================================================================ */
const CLUSTERS = ${JSON.stringify(CLUSTERS, null, 2)};
const CLUSTER_GROUPS = ${JSON.stringify(CLUSTER_GROUPS, null, 2)};
const LEVELS = ${JSON.stringify(CONFIG.LEVELS, null, 2)};
const RELATIONS = ${JSON.stringify(CONFIG.RELATIONS, null, 2)};
const RELEASE = ${JSON.stringify(CONFIG.RELEASE, null, 2)};
const GRAPH = ${JSON.stringify(GRAPH, null, 2)};
`;
  fs.mkdirSync(path.dirname(DATA_JS), { recursive: true });
  fs.writeFileSync(DATA_JS, out);
  const core = nodes.filter((n) => n.core).length;
  const bridges = resolved.filter((e) => e.bridge).length;
  console.log(`build ✓  ${nodes.length} nodes (${core} core), ${resolved.length} edges `
    + `(${bridges} curated bridges) · ${Object.keys(CLUSTERS).length} sub-clusters in `
    + `${CLUSTER_GROUPS.length} domains · tour ${flows.guidedPath.steps.length} · `
    + `${flows.comparisons.length} comparisons -> ${path.relative(ROOT, DATA_JS)}`);
  if (pending) console.log(`  ${pending} edges dropped (targets not emitted — CMNS/LCC/other domains)`);
}

const cmd = process.argv[2];
if (cmd === 'build') build();
else { console.error('Usage: node scripts/okf.js build'); process.exit(1); }
